### ISSUE TITLE
Rename repository to something else

### ISSUE THREAD

**Issue by borsna** [snd-sweden/Nccsv.Net#117]
New name: `nccsv-parser`(?)
@David-Rayner-GVC : any other suggestion for name?

This task should be done as a last step to avoid unnecessary config issues with local repositories.

**Comment by David-Rayner-GVC** [comment]
Might be a good idea to include something to differentiate from other possible nccsv parsers that might arise. 
nccsv-parser.net or .cs or # (not sure what is allowed in a repository name) to indicate c# might be good.
nccsv-parser# would be nice.

**Comment by borsna** [comment]
@David-Rayner-GVC having `C#` in the name is not realy relevant. the library can be used by any `.net` language.
To get more in line with other packages in nuget here is some suggestions:

* `Nccsv.NET`
* `NCCSV.NET`
* `NccsvParser.NET`

List of a few examples of other package names:
https://www.nuget.org/packages?q=spss&prerel=true&sortby=relevance
https://www.nuget.org/packages?q=geojson&prerel=true&sortby=relevance

@stefanjakobsson: any suggestions for a good package/repository name in "`.net`-style"?

**Comment by stefanjakobsson** [comment]
Maybe "Nccsv.Net"? Could be a good idea not to include "parser" in the name, in case we want to broaden the scope in the future?

**Comment by David-Rayner-GVC** [comment]
If I saw "Nccsv.Net" I would expect it could read and write nccsv. Maybe "NccsvReader.Net"? We could create a new package if we add write functionality?

**Comment by borsna** [comment]
Would prefer the name `Nccsv.Net` and make it clear in readme.md that current functionality is read only. Maintaining two repositories in the future should be avoided to reduce maintenance overhead.

**Comment by borsna** [comment]
Renamed to `Nccsv.Net`
